### ISSUE TITLE
finalizing methods for the ms: checking we can't use some of the data from Soolanayakanahally or Hall or Bongarten

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/localadaptclim#18]
@alinazeng I am starting an issue for this here as we finalize these in the manuscript file. Some to do items (I know you are likely working on these already) ...

- [x] Give the exact search terms
- [x] Give the day of the search

Also, we write that to be included papers had to, "report spring event in units of calendar days instead of a quantitative scale on a particular day, (c) report locations of provenances and gardens" -- can you expand on this a little? We need to explain why we could not back convert the quantitative scales to day of year (perhaps give an example in this issue so we can work on the text) and also give an example of papers that did not "report locations of provenances and gardens" ... what on earth did they do?

**Comment by alinazeng** [comment]
Hi Lizzie @lizzieinvancouver 

Below is a rough draft in response to your questions. Please let me know what you think and I will add them to our ms.
Question: for the examples that I gave below regarding what kind of papers were excluded... do we cite them like everything else?

We searched the peer-reviewed literature for common garden experiments that documented the timing of spring events of woody plant species. We searched on the Web of Science (Thompson Reuters, New York, NY) using all combinations of the following terms as ‘titles’ including ‘common garden*’ or “provenance*’ and ‘leafout*’ or ‘leaf out*’ or ‘budburst’ or ‘spring phenolog*’. Our search was limited to journal articles published before November 3, 2021. The search returned 94 publications. 

We read the methods and results of all publications returned and limited our subsequent analysis to the ones that (a) focused on woody plants originating from either Europe or North America, (b) reported spring events in units of calendar days (day of year or DOY) instead of a quantitative scale on a particular day, and (c) reported latitude and longitude of provenances and gardens. We had to exclude studies that reported spring events on a quantitative scale because (1) such studies usually only assessed where on the scale the spring event of a tree fell onto on the same days across different years (e.g. Robson et al., 2013; Vander et al., 2015; Santini et al., 2014; Schueler & Liesebach, 2004), and (2) scales are not always consistent across different studies. Such factors made it impossible to back convert the quantitative scale to DOY.

Some studies did not provide the exact latitude and longitude of the common garden (Bongarten, 1978) or the provenances (Hall et al., 2007; Soolanayakanahally et al., 2013), or they did not link the latitude and longitude of each provenance to the DOY of spring events (Deans and Harvey, 1996). We had to exclude these papers. Finally, studies that focused on examining how provenance altitude influenced local adaptation in spring phenology were excluded since we are interested in testing latitudinal effects (Vitasse et al., 2009; Vitasse et al., 2010; Li et al., 1997; Alberto et al., 2011; Acevedo-Rodríguez et al., 2006). 

Out of all papers related to common garden/spring phenology that we read, only 22 ultimately supplied the data that we needed (DOY of spring events, latitude, and longitude of provenances and common gardens); Out of the 22, four studies had provenance and gardens on different continents, which were subsequently archived (can document in supplements)).

**Comment by lizzieinvancouver** [comment]
> Some studies did not provide the exact latitude and longitude of the common garden (Bongarten, 1978) or the provenances (Hall et al., 2007; Soolanayakanahally et al., 2013)

Great work! I will work through these issues soon, but for now this point caught me -- I think we may need to consider whether we can include these studies, as reviewers will ask us to do so possibly. I know the Soolanayakanahally gives the towns, correct? If so we can extract lat/lon for each garden ... what does Bongarten, 1978 and Hall et al., 2007 give for info on the locations?

**Comment by alinazeng** [comment]
Hi Lizzie,
@lizzieinvancouver 
Soolanayakanahally does give the town, but they are using a scale system instead of doy. They conducted observations twice a week, during which they scored what they were seeing.

Similarly, Hall 2007 used a scale system too. They did not mention locations of provenances at all (no mention of city, no map, etc.). We actually emailed Hall last year but we never heard back.
Bongarten 1978 didn't provide location information for gardens and only stated which states in the US the provenances were in. 

I tried to include those papers, given we didn't have enough data at some point, but the lack of information on location does make it difficult to include them. What do you think?

**Comment by lizzieinvancouver** [comment]
@alinazeng Okay, it sounds like there is no way to recover the Hall or Bongarten data, but I could email Soolanayakanahally for their data as DOY and their exact provenances. I will try to do that soon.

**Comment by lizzieinvancouver** [comment]
@alinazeng No word on Soolananayakanahally after several emails and a deadline (past by a week) so I think we have to move forward without the data. I should review this issue when editing the methods and then I think we can close it.

**Comment by lizzieinvancouver** [comment]
We gave up on getting the Soolanananyakanahally data as it was slow in coming. Here's the email chain below (starting with my email on 31 January 2023):

> Hi Raju,
> 
> No worries! I have spent an insane number of hours this last week on finalizing some grant reports, so I know the feeling.
> 
> Thanks for the offer of the data, but we've moved ahead already on the analyses so we do not need it any more.
> 
> All the best,
> Lizzie
> 
> 
> On 1/30/23 4:28 PM, Soolanayakanahally, Raju (AAFC/AAC) wrote:
> > [CAUTION: Non-UBC Email]
> >
> > Hello Elizabeth,
> > I'm getting back to my emails this week.....
> >
> > For the last three weeks, I was completely occupied with two large-scale research grant application submissions (i10 Genome Canada (due on 20 Jan) and AAFC-Living Labs (due on 27 Jan). Hence, the delay & my sincere apologies.
> >
> > Please let me know if you are still interested in the phenology data.
> >
> > Thanks
> > -Raju
> >
> > -----Original Message-----
> > From: Elizabeth M Wolkovich [<wolkovic@mail.ubc.ca>](mailto:wolkovic@mail.ubc.ca)
> > Sent: January 12, 2023 12:29 PM
> > To: Soolanayakanahally, Raju (AAFC/AAC) [<raju.soolanayakanahally@AGR.GC.CA>](mailto:raju.soolanayakanahally@AGR.GC.CA)
> > Subject: Re: Soolananayakanahally et al. 2013
> >
> > CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
> > ATTENTION: Ce courriel provient de l’extérieur de l’organisation. Ne cliquez pas sur les liens et n’ouvrez pas les pièces jointes à moins que vous ne reconnaissiez l’expéditeur et que vous sachiez que le contenu est sûr.
> >
> > Dear Raju,
> >
> > Just following up to let you know we'll be finalizing data collection next week. So, if you can send data before next Friday (20 January) we'll include it. If you don't have time, I understand, and we'll move ahead without it. Thanks either way.
> >
> > All the best,
> > Lizzie
> >
> > On 1/7/23 5:06 PM, Elizabeth M Wolkovich wrote:
> >> Dear Raju,
> >>
> >> Happy New Year! I hope you had good holidays.
> >>
> >> I am just following up on my below email to ask if you might have time
> >> soon to send the data? My student and I are hoping to finish the paper
> >> soon.
> >>
> >> All the best,
> >> Lizzie
